aws:
  accessKeyId: YOUR_ACCESS_KEY_ID
  secretKey: YOUR_SECRET_ACCESS_KEY
  region: us-east-1

cloud:
  aws:
    stack:
      auto: false
    sqs:
      endpoint: http://localhost:4566
      queue:
        base-url: http://localhost:4566/queue/



